// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB67y6wz-cOFwuXseI1uELM48ZLXgHIDhA',
    appId: '1:935351147430:web:ab2e14254e54d5b5f2cd67',
    messagingSenderId: '935351147430',
    projectId: 'ai-color-palette',
    authDomain: 'ai-color-palette.firebaseapp.com',
    storageBucket: 'ai-color-palette.firebasestorage.app',
    measurementId: 'G-FM1WR260VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3zgqPQTNtDRRU0HDU_ShNyqn7x7UgMyY',
    appId: '1:935351147430:android:81e5c9262424ea13f2cd67',
    messagingSenderId: '935351147430',
    projectId: 'ai-color-palette',
    storageBucket: 'ai-color-palette.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDAPpJjSGAS7CgvGphCj-95bIahXunuYs',
    appId: '1:935351147430:ios:0c6a2c3a0ee0e6aff2cd67',
    messagingSenderId: '935351147430',
    projectId: 'ai-color-palette',
    storageBucket: 'ai-color-palette.firebasestorage.app',
    iosBundleId: 'com.example.aiColorPalette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDAPpJjSGAS7CgvGphCj-95bIahXunuYs',
    appId: '1:935351147430:ios:0c6a2c3a0ee0e6aff2cd67',
    messagingSenderId: '935351147430',
    projectId: 'ai-color-palette',
    storageBucket: 'ai-color-palette.firebasestorage.app',
    iosBundleId: 'com.example.aiColorPalette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB67y6wz-cOFwuXseI1uELM48ZLXgHIDhA',
    appId: '1:935351147430:web:3026ddc382065ccbf2cd67',
    messagingSenderId: '935351147430',
    projectId: 'ai-color-palette',
    authDomain: 'ai-color-palette.firebaseapp.com',
    storageBucket: 'ai-color-palette.firebasestorage.app',
    measurementId: 'G-9Z04FK3J41',
  );
}
